# Basic
title: Shudong Sun
subtitle: 
welcome_message: <a>Statistics and Data Science Ph.D. Student of The University of Arizona </a>
description: I am interested in the application of Data Science.
creator: <a href="http://shudongsun.github.io">@sunny</a>

url: "https://shudongsun.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: grey

# The blog button should not be removed.
blog_button:
    title: About me
    description: Know about me

# Navigation buttons in the front page.
nav:
    - {title: Resume, description: Resume, url: 'https://drive.google.com/file/d/1-G1YIp5aUCRJghPh9GiWIVIKTmthb0Be/view?usp=sharing'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: shudongsun
    # duoshuo: 
    
# Social
social:
    # github: shudongsun
    linkedin: shudongsun
    # gplus: 107108267983477358170
    mail: shudongsun@email.arizona.com

# Google Analytics
ga:
    id: UA-127400832-3
    # host: your_host
